Repository ZauJulio/Taskiano, pull requests merged in 2022-01, with the labels that each got.

#23 Adding doc of test coverage #17
  README.md
  docs/COBERTURA_TESTES.md
Labels: documentation

#21 Update README.md
  README.md
Labels: documentation

#25 Adding test unit of Update task
  taskiano/__tests__/Task.test.ts
Labels: enhancement

#26 Adicionando documento de requisitos
  README.md
  docs/Requisitos.md
Labels: documentation

#30 User CRUD Test
  taskiano/__tests__/User.test.ts
  taskiano/__tests__/lib/controllers/UserController.ts
  taskiano/__tests__/mocks/FireController.mock.ts
Labels: enhancement

#32 Fix eslint config
  taskiano/.eslintrc
  taskiano/package.json
Labels: bug

#35 Adicionando uma observação
  docs/COBERTURA_TESTES.md
Labels: documentation

#36 Adicionando observação
  docs/TESTE_INTEGRACAO.md
Labels: documentation

#37 Alterações na documentação e teste
  README.md
  docs/Requisitos.md
  docs/doc-userstories.md
  taskiano/__tests__/History.test.ts
Labels: documentation, enhancement

#39 Update doc and adding links to test of units
  docs/TESTE_UNIDADE.md
Labels: documentation

#40 Update docs user stories to USERSTORIES.md
  README.md
  docs/USERSTORIES.md
Labels: documentation
