Repository ZauJulio/Taskiano, pull requests merged in 2022-02, with the labels that each got.

#45 Adding Tests/unit project
  taskiano/__tests__/test/controllers/initialContext/ProjectInitialContext.test.ts
  taskiano/__tests__/test/schemas/ProjectSchema.test.ts
  taskiano/__tests__/test/services/ProjectService.test.ts
Labels: enhancement

#46 Fix mistakes in receveid values for initial context Project
  taskiano/__tests__/test/controllers/initialContext/ProjectInitialContext.test.ts
Labels: bug

#47 Tests/unit project
  taskiano/__tests__/test/controllers/initialContext/ProjectInitialContext.test.ts
  taskiano/__tests__/test/schemas/ProjectSchema.test.ts
  taskiano/__tests__/test/services/ProjectService.test.ts
Labels: enhancement

#48 Tests/unit task
  taskiano/__tests__/test/controllers/initialContext/TaskInitialContext.test.ts
  taskiano/__tests__/test/schemas/TaskSchema.test.ts
  taskiano/__tests__/test/services/TaskService.test.ts
Labels: enhancement

#50 Tests/unit task
  taskiano/__tests__/test/controllers/initialContext/TaskInitialContext.test.ts
  taskiano/__tests__/test/schemas/TaskSchema.test.ts
  taskiano/__tests__/test/services/TaskService.test.ts
Labels: enhancement

#51 Tests/unit history
  taskiano/__tests__/test/controllers/initialContext/HistoryInitialContext.test.ts
  taskiano/__tests__/test/schemas/HistorySchema.test.ts
  taskiano/lib/schemas/HistorySchema.ts
Labels: enhancement

#52 Root/tests
  taskiano/__tests__/it/lib/controllers/HistoryController.test.ts
  taskiano/__tests__/mocks/Repository.ts
  taskiano/__tests__/mocks/data/historys.ts
  taskiano/__tests__/mocks/data/tasks.ts
  taskiano/__tests__/test/controllers/initialContext/TasksInitialContext.test.ts
  taskiano/__tests__/test/schemas/UserSchema.test.ts
  taskiano/__tests__/test/services/UserService.test.ts
  taskiano/lib/controllers/HistoryController.ts
  yarn.lock
Labels: bug, enhancement

#53 Tests/unit history
  taskiano/__tests__/test/controllers/initialContext/HistoryInitialContext.test.ts
  taskiano/__tests__/test/schemas/HistorySchema.test.ts
  taskiano/lib/schemas/HistorySchema.ts
Labels: enhancement

#54 Root/tests: Add unit and integration tests for new arch
  taskiano/__tests__/it/lib/controllers/HistoryController.test.ts
  taskiano/__tests__/it/lib/controllers/ProjectController.test.ts
  taskiano/__tests__/mocks/Repository.ts
  taskiano/__tests__/mocks/data/historys.ts
  taskiano/__tests__/mocks/data/index.ts
  taskiano/__tests__/mocks/data/projects.ts
  taskiano/__tests__/mocks/data/tasks.ts
  taskiano/__tests__/test/controllers/initialContext/HistoryInitialContext.test.ts
  taskiano/__tests__/test/controllers/initialContext/ProjectInitialContext.test.ts
  taskiano/__tests__/test/controllers/initialContext/TaskInitialContext.test.ts
  taskiano/__tests__/test/controllers/initialContext/TasksInitialContext.test.ts
  taskiano/__tests__/test/schemas/HistorySchema.test.ts
  taskiano/__tests__/test/schemas/ProjectSchema.test.ts
  taskiano/__tests__/test/schemas/TaskSchema.test.ts
  taskiano/__tests__/test/schemas/UserSchema.test.ts
  taskiano/__tests__/test/services/ProjectService.test.ts
  taskiano/__tests__/test/services/TaskService.test.ts
  taskiano/__tests__/test/services/UserService.test.ts
  taskiano/lib/controllers/HistoryController.ts
  taskiano/lib/schemas/HistorySchema.ts
  taskiano/utils/toasts.ts
  yarn.lock
Labels: bug, enhancement

#56 Update documentation to test integration
  docs/TESTE_INTEGRACAO.md
Labels: documentation, enhancement

#57 Docs criados
  docs/COBERTURA_TESTES.md
  docs/TESTE_UNIDADE.md
Labels: documentation, enhancement
